### ISSUE TITLE
Opening tooltip randomly throws error

### ISSUE THREAD

**Issue by ceylina** [xmyno/Broker_WorldQuests#1]
Invalid quest item in SetQuestLogItem("type", index [, questID])

[C](?): in function `SetQuestLogItem'
Broker_WorldQuests\WorldQuests.lua:734: in function <Broker_WorldQuests\WorldQuests.lua:729>

I haven't been able to pinpoint when exactly this happens but it has happened a few times now.

This is the remainder of the error:

Locals:
(_temporary) = GameTooltip {
 0 = <userdata>
 FadeOut = <function> defined @TipTac\core.lua:906
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C](?):-1
 TMW_SetSpellByIDWithClassIcon = <function> defined @TellMeWhen\Components\Core\Spells\ClassSpellCache.lua:209
 SetUnitBuff = <function> defined =[C](?):-1
 SetQuestLogItem = <function> defined =[C](?):-1
 hasMoney = 1
 shownStatusBars = 0
 SetIconTextureAndText = <function> defined @TipTacItemRef\core.lua:53
 ttIcon = <unnamed> {
 }
 SetHyperlink = <function> defined =[C](?):-1
 updateTooltip = 0.18399999924004
 numStatusBars = 1
 shoppingTooltips = <table> {
 }
 ttCount = <unnamed> {
 }
 __tamedCounts = false
 SetUnitAura = <function> defined =[C](?):-1
 Show = <function> defined @TipTac\core.lua:920
 SetUnitDebuff = <function> defined =[C](?):-1
 comparing = false
 needsReset = true
 SetQuestItem = <function> defined =[C](?):-1
 SetRecipeResultItem = <function> defined =[C](?):-1
}
(_temporary) = "reward"
(_temporary) = 1
(_temporary) = 44002

**Comment by xmyno** [comment]
Seen it, but haven't found a solution nor a reliable way to reproduce it. I'll keep looking!
