### ISSUE TITLE
7.1.28 - tooltip while holding shift gets stuck with broker tooltip closed

### ISSUE THREAD

**Issue by ceylina** [xmyno/Broker_WorldQuests#10]
Quite often and sometimes caused by mousing over the broker tooltip and getting into combat, the items shown that have tooltips will have the last one stuck when holding down shift anywhere on screen. the only solution is to reload the UI

so here is a sample broker tooltip display
![wowscrnshot_111416_120602](https://cloud.githubusercontent.com/assets/9342192/20276780/5c35d2a0-aa63-11e6-9989-f4f200f78af3.jpg)

Here is a screenshot of a loose tooltip after pressing shift on the screen with the broker display not showing

![wowscrnshot_111416_120605](https://cloud.githubusercontent.com/assets/9342192/20276796/77060b5e-aa63-11e6-902a-cb3282bcfa54.jpg)

**Comment by xmyno** [comment]
Good catch, I'll work on a fix.
I guess the modifier changed event gets stuck somehow after pressing shift so I just need to make sure it gets unregistered properly.

**Comment by xmyno** [comment]
Sorry for the wait. Should be fixed in 7.1.29 (https://github.com/xmyno/Broker_WorldQuests/commit/99c502ad1d61bc8ff734faec00abd21a99e68951).
