### ISSUE TITLE
AP available is showing incorrect numbers

### ISSUE THREAD

**Issue by Ressym** [xmyno/Broker_WorldQuests#13]
As soon as I hit AK36, any AP amounts which were supposed to hit double digits (ie 10 mil or higher), were showing as 10x the amount it should have been.  Every other AP reward amount was showing correctly.
I've attached a screenshot I took in game, both highlighted AP rewards were supposed to be 10.5 mil each, but were showing as 105 mil each.

![world quest](https://cloud.githubusercontent.com/assets/28846969/26287277/46e6522c-3e46-11e7-9270-d55804a9ec98.png)

**Comment by xmyno** [comment]
Pushed a fix in develop (https://github.com/xmyno/Broker_WorldQuests/commit/947d05f59a9d2416e35f00e055c5727ea815eb8a). Would be great if you can find time to test it and tell me if that's working properly, because I currently don't have an active subscription to test it myself.

**Comment by Ressym** [comment]
Looks great. Numbers are showing perfectly.  Thanks for the quick response! :)

**Comment by xmyno** [comment]
Just noticed I can just test this on PTR, found a few issues with other locales that need fixing :)
