### ISSUE TITLE
7.3 Argus not showing up

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#14]
The three zones of Argus in 7.3 also have world quests.
Those are unlocked by questing, similiar to the broken shore world quests that are unlocked by the intro quest.
Anything else than the 3 zone numbers you require here? Do you want to tie it to the specific spells/quests per part of the zone?

**Comment by xmyno** [comment]
Probably just have to add the zone ids, yes. I'll take a look at it tomorrow. If it's anything like in the past the world quests only get returned from the API if they're unlocked, so hopefully no need for spell ids.

Are there any new currencies or something else to add that I should know about?

**Comment by yoshimo** [comment]
In addition to war supplies and nether shards we now buy gear with https://github.com/eTzmNcbkrng/SavedInstances/issues/30#event-1224433993

**Comment by yoshimo** [comment]
[1135] = true, -- Krokuun
[1170] = true, -- Mac'Aree
[1171] = true, -- Antoran Wastes

**Comment by alcaras** [comment]
Worth also noting that it looks like Argus quests are behind a different main map than the rest of the Broken Isles, so a bit more finagling may be needed to get to them.

**Comment by xmyno** [comment]
Released 7.3.40 which adds the new maps and has some bug fixes.
