### ISSUE TITLE
Battle for Azeroth data

### ISSUE THREAD

**Issue by xmyno** [xmyno/Broker_WorldQuests#19]
I will need some help in regards to everything that will be new in BfA that affects world quests on level 120. That includes:

* zones
* factions (if there's a similar system like in Legion)
* currencies
* resources
* special gear (?)

Names are most likely enough. I should be able to find the rest by using wowhead/PTR etc.

Also I'm intending to remove 110 world quest data completely and replace it with the new 120 stuff for ease of maintenance. Old world quests should become irrelevant, correct?

**Comment by yoshimo** [comment]
I wouldn't remove it, there are always people that still do old content for sake of completeness and achievements. I would say show the maximum level of world quests that you have unlocked by default and offer the player to show worldquests of lower expansions on request.

**Comment by yoshimo** [comment]
We have the same system as in Legion where quests are associated with factions and if you do 3/4 of them, you get a special reward:
Up are for me today:
Talanjis Expedition (http://www.wowhead.com/faction=2156/talanjis-expedition)
Voldunai (http://www.wowhead.com/faction=2158/voldunai)
Tortollan Seekers (http://www.wowhead.com/faction=2163/tortollan-seekers)


Zones affected are:
Horde:
- Nazmir (id:863)
- Vol'dun (id:864)
- Zuldazar (id:862)

Alliance:
- Tiragarde (id:895)
- Stormsong Valley (id:942)
- Drustvar (id:896)

Horde can do WQs on alliance zones as well, because they got outposts there and vice versa

Rewards cover:
- azerite power
- reputation commendations with the various BFA factions
- war ressources
- gold
- armor items of at least blue quality

**Comment by xmyno** [comment]
Thanks for the info!

I've written a basic expansion-toggle. Could you check out the bfa-120 branch (https://github.com/xmyno/Broker_WorldQuests/tree/feature/bfa-120) and test that on the beta if it's showing anything? Rewards etc. isn't done yet, just would like a confirmation if any quests show up (or errors :P)

**Comment by yoshimo** [comment]
Affecting world quests as well are contracts like:
http://www.wowhead.com/item=153665/contract-talanjis-expedition

>Enter a contract with Talanji's Expedition that allows you to gain reputation with them every time you >complete a world quest on Kul Tiras and Zandalar.

**Comment by yoshimo** [comment]
So we get results on the bfa branch:

![broker_wq_bfa_branch](https://user-images.githubusercontent.com/17909/43734855-53d59be4-99b9-11e8-9548-0611af58039c.jpg)

The quests without reward column mostly reward azerite power, war resources or reputation
Reputation seems to be handled via currencies on the follower mission table
http://www.wowhead.com/currency=1597/zandalari-empire
http://www.wowhead.com/currency=1600/honorbound

I assume similiar things for the world quest rewards. 
http://www.wowhead.com/hidden-currencies
http://www.wowhead.com/battle-for-azeroth-currencies

**Comment by NLZ** [comment]
There will be WQs in Arathi (ID:14) as well, right?

**Comment by yoshimo** [comment]
well it is a warfront and contested between Horde and Alliance, but so far i haven't seen worldquests there yet. I will join the fight later tonight and see how it works.

**Comment by yoshimo** [comment]
More about world quests ,factions and rewards:
http://www.wowhead.com/guides/battle-for-azeroth-world-quests
Rewards also include:
http://www.wowhead.com/item=163857

**Comment by xmyno** [comment]
Updated the branch with the first batch of new factions and currencies. If you have time give it a try.

**Comment by yoshimo** [comment]
The reward column is completely empty now
Not even gold is listed anymore.

**Comment by xmyno** [comment]
No errors?

**Comment by xmyno** [comment]
Found two more mistakes. 614029d46862eb11de3b0de6ad1b415c7f10c7f6

**Comment by yoshimo** [comment]
There were a couple of errors last night, but so far they didn't get attributed to Broker WQ.
AskMRRobot reported problems with getting the player spec. Details complained about undefined "?" and db entries, LFG didn't like the castration of groupfinding apis in the last build and libsink was broken somehow.
Nothing Broker_WQ did report.

Regarding the Arathi Highlands.
This seems more like an instanced battleground than worldquests. It is opened up by doing enough daily quests in Zuldazar/Kultiras to launch the onslaught.

**Comment by xmyno** [comment]
Did you try with the latest commit? Otherwise I'll have to take another look if I can spot anything else in the dry-coded BFA parts that could be causing it.

**Comment by yoshimo** [comment]
I haven't tried the version 614029d from 19h ago yet, not at a computer for a couple more hours

**Comment by yoshimo** [comment]
It is almost fine with the fixes you pushed yesterday
![bwq_tooltip2](https://user-images.githubusercontent.com/17909/43917187-d89d1b60-9c0f-11e8-8744-bc2648febc90.jpg)
![bwq_samplequest](https://user-images.githubusercontent.com/17909/43917200-e533cc20-9c0f-11e8-9b28-eea23628902d.jpg)
The Quests with reputation rewards show their faction, but the amount is 0 and there is just a green placeholder graphic

For some reason some items have no itemlevel attached.
It is azerite gear:

![bwq_azerit_item1](https://user-images.githubusercontent.com/17909/43917484-c1423db4-9c10-11e8-8607-f49b24e026ff.jpg)
![bwq_azerit_item2](https://user-images.githubusercontent.com/17909/43917486-c16e101a-9c10-11e8-8932-51999ea14da4.jpg)

**Comment by yoshimo** [comment]
Azerite gear can be boosted by 5 itemlevels if your heart of azeroth is powerfull enough to unlock the last tier ring of the item.

**Comment by xmyno** [comment]
I'll see if I can fix the reputation.
Can you show me a screenshot of the reward for "Gulliver" "Kopfbedeckung des Seefahrers"? This looks like there's something missing

**Comment by xmyno** [comment]
Meh just a typo bef4334f6802076243766d59ef661ebc29ade7e2

**Comment by yoshimo** [comment]
![bwq_tooltip3](https://user-images.githubusercontent.com/17909/43919651-dea65aec-9c16-11e8-91fc-bf5082db7e00.jpg)

**Comment by xmyno** [comment]
Item level display is fixed.

Still need to have a look at war mode reward multiplying.

**Comment by yoshimo** [comment]
I stand corrected: there are world quests in arathi IF your faction controls it.
For the horde you get:
https://www.wowhead.com/quest=52848/the-lions-roar#comments
The alliance has to face https://www.wowhead.com/quest=52847/dooms-howl

**Comment by yoshimo** [comment]
@xmyno Itemlevel for relicts in legion is not shown, bfa-content looks fine for now

**Comment by xmyno** [comment]
I noticed that, but it will be low priority since it's old content and needs a different method of acquiring the item level.

I've released the current state for now. Again, thanks for your help! :)

**Comment by yoshimo** [comment]
It also might be useful to add it for
https://www.wowhead.com/item=163857/azerite-armor-cache to see what itemlevel is inside.

**Comment by NLZ** [comment]
Do we have information on what the ilvl is the item in it?

**Comment by yoshimo** [comment]
![azerite](https://user-images.githubusercontent.com/17909/43994941-80b5b028-9da5-11e8-835b-00750089036f.jpg)

**Comment by yoshimo** [comment]
The chest has the same dynamic itemlevel as the reward
