### ISSUE TITLE
Tooltip overlay confliction

### ISSUE THREAD

**Issue by Bram91** [xmyno/Broker_WorldQuests#2]
When I hover over an item and I want to compare it to my currently equiped item the text from the broker overlays the comparison screen. 

A possible fix is to change line 109 from:
`BWQ:SetFrameStrata("TOOLTIP")`
to
`BWQ:SetFrameStrata("HIGH")`

Would be nice if you can include it in an upcoming release. Currently not on my development machine so cant easily do a pull request :)

**Comment by xmyno** [comment]
Setting it to HIGH makes it show below certain frames like the WorldMapFrame, I'm not sure if I want it to be like that.
I've solved it originally by increasing FrameLevel of the tooltip, but forgot to do the same for the compare tooltips. I think I will stick with that solution (and obviously adjust the other tooltips).

**Comment by xmyno** [comment]
Should be fixed.

**Comment by Bram91** [comment]
Will check once I get home :)
