### ISSUE TITLE
Doing WQ 

### ISSUE THREAD

**Issue by sgkdnay** [xmyno/Broker_WorldQuests#20]
1x Broker_WorldQuests\WorldQuests.lua:444: attempt to index global 'WorldMapUnitPositionFrame' (a nil value)
Broker_WorldQuests\WorldQuests.lua:444: in function `CalculateMapPosition'
Broker_WorldQuests\WorldQuests.lua:460: in function <Broker_WorldQuests\WorldQuests.lua:447>
Broker_WorldQuests\WorldQuests.lua:1095: in function <Broker_WorldQuests\WorldQuests.lua:1094>

Locals:
self = Broker_WorldQuests {
 0 = <userdata>
 bountyCache = <table> {
 }
 totalMining = 0
 totalResources = 5160
 RunUpdate = <function> defined @Broker_WorldQuests\WorldQuests.lua:986
 UpdateBlock = <function> defined @Broker_WorldQuests\WorldQuests.lua:995
 totalFishing = 1
 UpdateBountyData = <function> defined @Broker_WorldQuests\WorldQuests.lua:803
 AttachToBlock = <function> defined @Broker_WorldQuests\WorldQuests.lua:1568
 RenderRows = <function> defined @Broker_WorldQuests\WorldQuests.lua:899
 mapTextures = BWQ_MapTextures {
 }
 slider = <unnamed> {
 }
 GetItemLevelValueForQuestId = <function> defined @Broker_WorldQuests\WorldQuests.lua:317
 AddFlightMapHook = <function> defined @Broker_WorldQuests\WorldQuests.lua:1564
 ShowNoWorldQuestsInfo = <function> defined @Broker_WorldQuests\WorldQuests.lua:266
 UpdateQuestData = <function> defined @Broker_WorldQuests\WorldQuests.lua:868
 totalSkinning = 0
 totalArtifactPower = 0
 SetupConfigMenu = <function> defined @Broker_WorldQuests\WorldQuests.lua:1400
 totalGold = 33319500
 totalLegionfallSupplies = 175
 GetArtifactPowerValue = <function> defined @Broker_WorldQuests\WorldQuests.lua:281
 totalHonor = 1400
 WorldQuestsUnlocked = <function> defined @Broker_WorldQuests\WorldQuests.lua:239
 QueryZoneQuestCoordinates = <function> defined @Broker_WorldQuests\WorldQuests.lua:429
 totalHerbalism = 0
 WorldQuestsBroker = <table> {
 }
 totalBloodOfSargeras = 5
 totalWakeningEssences = 333
 bountyDisplay = BWQ_BountyDisplay {
 }
 totalGear = 17
 CalculateMapPosition = <function> defined @Broker_WorldQuests\WorldQuests.lua:443
 AttachToWorldMap = <function> defined @Broker_WorldQuests\WorldQuests.lua:1583
 OpenConfigMenu = <function> defined @Broker_WorldQuests\WorldQuests.lua:1543
}
x = 0.38017416000366
y = 0.27396863698959
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WorldMapUnitPositionFrame' (a nil value)"

**Comment by xmyno** [comment]
Should be fixed. This was related to the highlight arrow when clicking a quest and it's now working again too!

Thanks for the report.
