### ISSUE TITLE
Slightly wrong info in the tooltip about unlocking worldquests

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#21]
I am 120 on the beta realm and the tooltip says "you need to be 110 to unlock worldquests"

It should be more detailed 

- 110 and finishing uniting the isles for Legion Broken Isle worldquests (43341 with rep requirements and 45727 without for alts once the former has been completed on any char on the account)
- finishing a certain step in the War of Thorns Pre-BFA Event to unlock the dark shore quests
- reaching 120 and turning in Uniting Zandalar (id:51916/52451) unlocks world quests on Zandalar for the Horde
This also completes the Alliance counterpart Uniting Kul Tiras (id:51918/52450) and ID:51722 which has no known name yet.

**Comment by xmyno** [comment]
Took the quest requirement out when they added the main-only reputation thingy (937c76f69e49ab45705bf9993a9598709fad5bce) and I seem to have missed that there are two separate quest IDs for unlocking. I'll add that when I'm done with 120-stuff.

Not sure how to handle pre-BFA event world quests. Do they disappear when BFA launches? If so I'll ignore that and only add the unlock-check when BFA is live and worry about it if there's ever a similar situation.

**Comment by yoshimo** [comment]
It seems that the DarkShore worldquests will disappear on launch date, so it probably doesn't matter for the next 9 days.

**Comment by yoshimo** [comment]
As you can see the unlock quests for BFA zones are already set up with the same scheme so that alts do not need the reputation requirements to get world quests active

**Comment by yoshimo** [comment]
Darkshore has worldquests as long as your faction controls it.
