### ISSUE TITLE
Enable localised text

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#22]
When i read the code i found lines like

`quest = "|cffffff00|Hquest:51918:-1|h[Uniting Kul Tiras]|h|r"`

`SetText(("You need to reach Level %s and complete the\nquest %s to unlock World Quests."):format(level, quest))
`
For people that prefer their own mother tongue, it might be a good idea to be able to translate those and the various filtering options

**Comment by xmyno** [comment]
Maybe in the future, but until now I was too lazy to implement localization since it only affects small parts of the functionality (mainly settings and some messages). And just having the quest name localized in between non-translated english texts would be weird too. :D

**Comment by yoshimo** [comment]
It won't break usability that much, i just think it feels weird if your UI is completely italian, german,french or russian and then one part sticks out. Therefore a fully translated interface might be more appealing for some

**Comment by Amadeus-** [comment]
If someone would like to submit a pull request to add this feature, I'll be happy to integrate it.  But, neither the original author nor myself have the time or motivation to do so.  (It's a free product and we're volunteers, after all.)
