### ISSUE TITLE
Bug: Usage: GameTooltip:SetHyperlink(link)

### ISSUE THREAD

**Issue by Treacherouz** [xmyno/Broker_WorldQuests#23]
Message: Usage: GameTooltip:SetHyperlink(link)
Time: Sun Aug 12 10:51:05 2018
Count: 35
Stack: Usage: GameTooltip:SetHyperlink(link)
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...ce\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:412: in function <...ce\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406>
[C]: in function `SetHyperlink'
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:462: in function <Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:456>
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1264: in function <Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1260>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetSpellBookItem = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 ZGV_ShowManyLines = <function> defined @Interface\AddOns\ZygorGuidesViewer\Functions.lua:253
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 progressBarPool = <table> {
 }
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetPetAction = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetUnitDebuff = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 __tamedCounts = false
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 CIMI_tooltipWritten = false
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTalent = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetTradePlayerItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 updateTooltip = 0.023999988846481
 SetInventoryItem = <function> defined =[C]:-1
 SetShapeshift = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetUnitBuff = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetLootRollItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetItemByID = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetRecipeResultItem = <function> defined @Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:406
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = nil

**Comment by xmyno** [comment]
Can't reproduce at the moment even with Informant installed.

**Comment by qualitaz** [comment]
I keep getting a similar error when hovering a select few WQ rewards.
Most of the time its limited to petbattle rewards like the pet bandages or charms, but now when I'm trying to figure out the cause of it, it seems to give me errors on Mechagon reagent rewards and Nazjatar item tokens aswell.
I dont have any other rewards left in the list except for gold/AP/GR at the moment, so cant say for sure that it is limited to the mentioned stuff, but I know I saw tooltips for normal items when I ran around for them earlier.


Usage: GameTooltip:SetHyperlink(link)
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
Broker_WorldQuests\WorldQuests.lua:539: in function <Broker_WorldQuests\WorldQuests.lua:533>
Broker_WorldQuests\WorldQuests.lua:1598: in function <Broker_WorldQuests\WorldQuests.lua:1594>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetTrainerService = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 __tamedCounts = false
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetTradeTargetItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetQuestLogItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 updateTooltip = 0.180000
 SetInventoryItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 comparing = false
 SetLootRollItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = nil

------------------------------------------------

EDIT:
With only TitanPanel and Broker_WorldQuests activated:


Message: Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:539: Usage: GameTooltip:SetHyperlink(link)
Time: Fri Dec 13 16:54:41 2019
Count: 3
Stack: Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:539: Usage: GameTooltip:SetHyperlink(link)
[C]: in function `SetHyperlink'
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:539: in function <Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:533>
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1598: in function <Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1594>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 updateTooltip = 0.009000
 comparing = false
 shoppingTooltips = <table> {
 }
 TopOverlay = <unnamed> {
 }
 ItemTooltip = <unnamed> {
 }
 needsReset = true
 BottomOverlay = <unnamed> {
 }
}
(*temporary) = nil

------------------------------------------------

EDIT 2

Now that I have other WQs back in the list with actual items, there are no errors on any of the items.
Will update this post with new findings if I clear them out again and find new errors.

**Comment by qualitaz** [comment]
Separating this in a new comment for easier viewing.

Error needs a few things to be true to be reproduced.
The pet charms/bandages and presumably any other non-item links needs to be the only thing in the list when logging in.

If you have cleared out the list of items, they will still give working tooltips when hovering them as long as you haven't logged out yet, but as soon as you log out and back in with those "items" in the list, the errors will start showing up, and it wont show the tooltips.

EDIT:
Having an AP emissary in the list does not stop the errors - might work if there are items from an emissary reward, but that will have to wait until one is up.

A quickfix to get rid of the errors for the current logged in session is to swap to the Legion WQ list to let the addon handle the defining of hyperlinks and then swapping back to the BFA list to avoid errors for the rest of that session.

**Comment by Amadeus-** [comment]
I'm going to assume this got fixed somewhere along the line.   But, if it does happen again, please go over to the new "official" repository at https://github.com/Amadeus-/Broker_WorldQuests and open a new issue there.
