### ISSUE TITLE
Filter by rewards

### ISSUE THREAD

**Issue by Oz5tor** [xmyno/Broker_WorldQuests#27]
Hi when un-checking rewards the WQ'lists is not changing at all to the news filters.

i have unselected high and low gold + Rep rewards, gut they are still showing up on both lists

https://i.imgur.com/njQUM05.png

Curruntly using version 8.0.50 from the Twitch app.

**Comment by xmyno** [comment]
"Always show quests for faction" overrides the reward filters, which is why they all keep showing.

**Comment by Oz5tor** [comment]
did not think it was programmed that way, well i would not have xD. Thanks

**Comment by xmyno** [comment]
That's the meaning of the word "always".
