### ISSUE TITLE
Zone separator problem

### ISSUE THREAD

**Issue by Tarkumi** [xmyno/Broker_WorldQuests#28]
If you change expansion from Battle for Azerot to Legion or vice versa the zone separators stays from the other panel and makes hard to select the world quest on the current panel.
Even worse if you click on this invisible separator, the zone collapses on the other panel.
On the two attached images you can see the BfA zone separator's position on the Legion panel. When you click on that invisible separator and switch back to Bfa, Vol'dun will be collapsed.
![bfa](https://user-images.githubusercontent.com/455295/45501804-88968f00-b782-11e8-96ae-8268c5451066.jpg)
![legion](https://user-images.githubusercontent.com/455295/45501806-8c2a1600-b782-11e8-95e7-e3f61a81ab7d.jpg)

**Comment by xmyno** [comment]
Should be fixed.
