### ISSUE TITLE
Arathi Highlands : Weekly Tank world quest missing

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#29]
When the horde has taken over the arathi highlands and the alliance is collecting ressources to get it back, you can fight once every ~weeks the alliance tank in a world quest.
Although i have enabled "show epic quests always" and only hidden quests with reputation tokens and gear i can't see the arathi world quest in the broker menu.
The other world boss in Zuldazar and Kultiras show perfectly fine.

**Comment by xmyno** [comment]
Should be visible now. Some world quests now have a timeleft of 0, which is why they got filtered out.
