### ISSUE TITLE
Incursions?

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#32]
I am not sure what to do with those, but regardless of having checked all rewards buttons, i can't see them.
Not sure if i should with the last update.

```QuestID worldQuestType
54308 12
54434 12```

```
/run for key, value in pairs (_G) do if type(key) == "string" and key:find ("LE_QUEST_TAG") then print (key, value) end end

LE_QUEST_TAG_TYPE_INVASION_WRAPPER 11
LE_QUEST_TAG_TYPE_DUNGEON 6
LE_QUEST_TAG_TYPE_INVASION 7
LE_QUEST_TAG_TYPE_TAG 0
LE_QUEST_TAG_TYPE_PROFESSION 1
LE_QUEST_TAG_TYPE_NORMAL 2
NUM_LE_QUEST_TAG_TYPES 14
LE_QUEST_TAG_TYPE_ISLANDS 13
LE_QUEST_TAG_TYPE_BOUNTY 5
LE_QUEST_TAG_TYPE_PET_BATTLE 4
LE_QUEST_TAG_TYPE_PVP 3
LE_QUEST_TAG_TYPE_FACTION_ASSAULT 12
LE_QUEST_TAG_TYPE_RAID 8
LE_QUEST_TAG_TYPE_INVASION_WRAPPER 11
LE_QUEST_TAG_TYPE_DUNGEON 6
LE_QUEST_TAG_TYPE_INVASION 7
LE_QUEST_TAG_TYPE_TAG 0
LE_QUEST_TAG_TYPE_PROFESSION 1
LE_QUEST_TAG_TYPE_NORMAL 2
NUM_LE_QUEST_TAG_TYPES 14
LE_QUEST_TAG_TYPE_ISLANDS 13
LE_QUEST_TAG_TYPE_BOUNTY 5
LE_QUEST_TAG_TYPE_PET_BATTLE 4
LE_QUEST_TAG_TYPE_PVP 3
LE_QUEST_TAG_TYPE_FACTION_ASSAULT 12
LE_QUEST_TAG_TYPE_RAID 8
```

**Comment by xmyno** [comment]
![image](https://user-images.githubusercontent.com/1918058/50060330-df9d6d00-0192-11e9-8918-88c260b2fd13.png)

They do show up for me (I only added the icon just now).

**Comment by yoshimo** [comment]
Yea they do, i just didn't identify them as such because the conquest point reward isn't shown.
Maybe you need to add https://www.wowhead.com/currency=1602/conquest as a possible reward type.

**Comment by xmyno** [comment]
Icon for Incursions and Conquest is added in the new version (8.1.52).
Also some new features included! (Paragon reputation bars, bounty reward hover, expansion quick-switch)
