### ISSUE TITLE
Error since 8.1.5 patch.

### ISSUE THREAD

**Issue by Cluuey** [xmyno/Broker_WorldQuests#35]
Hi xmyno,
I'm getting the following errors with only my broker display, Bugsack, Buggrabber and Broker_Worldquests.
It happens with the cursor over the emissary area at the top of the list.

Apparently `WorldMapTooltip` has been removed so I commented out lines 1028,1029 and the block 1056-1075.
This has stopped the errors but I don't know if that is all that needs doing.
Obviously the emissary tooltip doesn't work.

```12x Broker_WorldQuests\WorldQuests.lua:1029: attempt to index global 'WorldMapTooltip' (a nil value)
Broker_WorldQuests\WorldQuests.lua:1029: in function <Broker_WorldQuests\WorldQuests.lua:1029>

Locals:
self = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WorldMapTooltip' (a nil value)"
```

**Comment by xmyno** [comment]
Fixed a while ago but forgot to close the issue. :)
