### ISSUE TITLE
some debug funkctions would be nice

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#36]
When i go over new content on the test realms, i often struggle to see what needs to be done in BWQ to adjust for new zones.

It would be great to have a debug option that dumps all worldquest related data for a given zone id to chat name,questid, rewards and so on associated with a marker if BWQ knows about the various infos about. Sometimes they introduce new quest types, new factions, new currencies or rewards and i wonder if it still needs to be added to this addon so we can filter properly and show all rewards properly.
figuring out where to add print-statements takes time again for each patch.
Maybe you can help here.

**Comment by xmyno** [comment]
Sorry for the late reply. I've stopped playing again a while ago, so I'll have to see if I can add some and test it on PTR if it's still up.

**Comment by yoshimo** [comment]
It was up a few hours ago

**Comment by xmyno** [comment]
There is now a debug flag at the top of the WorldQuests.lua file.
https://github.com/xmyno/Broker_WorldQuests/blob/develop/WorldQuests.lua#L41

At the moment, if set to true it will print unhandled currencies and quests that had no reward set at all. No reward *might* be correct though, but I couldn't think of a way of distinguishing that case.

**Comment by Amadeus-** [comment]
@yoshimo I'm assuming you were OK with the debug flag that xmyno added in 2020.   If you need more debug information, please feel free to open a new issue at the new "official" repository at https://github.com/Amadeus-/Broker_WorldQuests.   Or, you can fork that repository and create a pull request against it.
