### ISSUE TITLE
Doesn't Filter...

### ISSUE THREAD

**Issue by vandiel01** [xmyno/Broker_WorldQuests#39]
I turned off Dungeon "search" filter and still showing them

![image](https://user-images.githubusercontent.com/52209920/61073924-127faa80-a3dc-11e9-9ccf-a9a1f5d33842.png)

**Comment by xmyno** [comment]
You probably have "Always show quests for active bounty" active. This overrides the filters.

**Comment by vandiel01** [comment]
![image](https://user-images.githubusercontent.com/52209920/62338803-6cd1cf80-b49f-11e9-8272-ea86c58d38eb.png)
