### ISSUE TITLE
A few suggestions for your consideration

### ISSUE THREAD

**Issue by papasoldragon** [xmyno/Broker_WorldQuests#4]
This addon is amazing, I thank you for this work. I find this a necessary tool in my daily grind. Thank you for making this. I do have some suggestions though that would help my play style a bit more. I think these changes would help to further evolve the addon for other users as well so here they are:

Flight Master Map Support:
- Enable an option to show the frame on the flight master map just like the world map. The frame is larger than the world map and is a static/non-draggable frame that centers on your screen. This means you would need to adjust where the frame is further to the left so your frame fits nicely to the right.
- The flight master map also displays world quests. However, you have to zoom in to see them which is a bit annoying. If possible, I'd like to see these icons promoted to the zoomed out frame to better plan out my pathing choices for the day.
- This feature may also require a retooling of the frame when on the Flight Master Map so that clicking on quests selectes them in the Flight Master Map when shown instead of opening the World Quest map. 

World Map Suggestion:
- I use this feature most of all. However, when I know my route I often leave the world map open to guide myself through unfamiliar zone, which everything is unfamiliar right now due to being new. I would like to see a simple close frame button on the frame that is appended tot he Word Map so that you can close out the world quests frame but leave the world map open. Reopening the world map would reopen the world quest frame. I could also see this feature being a toggle on the world map frame which shows and hides the world quest frame. Maybe even slides it under and out from the world quest when hiding and showing. Many ways to handle this.
- If you added the show/hide frame support to the World Quest Frame & Enable support for the Flight Master Map as suggested above, The same show/hide world quest frame feature could be used on the Flight Master Map as well.

Thanks again for you work on this magnificent addon. The table you've created is ascetically pleasing to the eye and very functional. I roll with allot of addons and played many years of WOW. I only make suggestion for great addons that I enjoy. Please don't take this as a criticism of your work. You've done an excellent job as it is and these suggestions would just be icing on an already fabulous cake.

**Comment by xmyno** [comment]
Thanks for the nice words, I'll keep your suggestions in mind :)
