### ISSUE TITLE
Dailies in an extra dropdown

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#44]
With 8.2 a lot of quests appeared that are as important as worldquests for your progress but are marked daily.
They can be received from the getquestsbymapid() function and have an isdaily marker. Nazjatar and Mechagon are affcted, with 8.3 this extends to Valley of Eternal Blossoms and Uldum.

It would be nice to have this as a ldb feed too.

**Comment by Amadeus-** [comment]
Is this still something that you think would benefit the addon?   Or, was it really just something that would have benefited the addon back during the 8.x time and isn't as important in current content?

If so, please feel free to open a new request/issue under the new official Broker_WorldQuests repository at https://github.com/Amadeus-/Broker_WorldQuests

Thanks!
