### ISSUE TITLE
Shadowlands support

### ISSUE THREAD

**Issue by xmyno** [xmyno/Broker_WorldQuests#48]
### World Quest Unlock 
World Quests are available on the following conditions
* You did your personal covenant quest chain at level 60 and unlocked world quests that way.
* One of your other characters reached 60 and you choose the fast track in `Threads of Fate` after leaving the maw with level 51

* [ ]  Unlock conditions for Shadowlands world quests
  * [ ]  Night Fae
  * [ ]  Kyrians
  * [ ]  Venthyr
  * [ ]  Necrolords

### Rewards
* [ ]  Format bonus experience currency in SL is wrong
    * Does it make sense to have experience in currency?
    * Are these only when you are skipping and do them from 51-60?
* [ ] Check if any rewards are missing

### Filters
* [ ] Find items, currencies etc. that are worth including in filters (and in broker text)
* [ ] Move BFA filters into submenu

### Bounty

* [ ] Add map id for retrieving bounties

### Achievements

* [x] Battle in the Shadowlands (Pet Battle)

**Comment by yoshimo** [comment]
We need to also make sure that 51 is the lowest possible level for wqs. I reached 51 on a few chars after coming to bastion.
Could have been "play main story" as well though.

**Comment by yoshimo** [comment]
Thanks to wowhead i think that part becomes easy
https://shadowlands.wowhead.com/achievement=14807/hidden-completed-shadowlands-story-dnt-account
mentions 
> Once earned, a player's alt can access the Shadowlands Time Skip mode. (DNT) 

I would either check for the achievement or `Quest: 62706`

https://shadowlands.wowhead.com/achievement=14811/hidden-shadowlands-alt-launch-chromie-if-shadowlands-in-progress-dnt /  `Quest: 62713` is probably something else.

To see which quest needs to be done to complete the "WQ Unlock Quest ", aka 57559
 maybe we could check these:
```
G[62017]=''	-- Yoshimo: probably NECROLORDS COVENANT
G[62019]=''	-- Yoshimo: probably NIGHT FAE COVENANT
G[62020]=''	-- Yoshimo: probably VENTHYR COVENANT
G[62023]=''	-- Yoshimo: probably KYRIAN COVENANT
```
or maybe C_Covenants.GetActiveCovenantID() , although i don't know which number which covenant is yet

**Comment by yoshimo** [comment]
Venthyr/Revendreth Unlock
https://shadowlands.wowhead.com/quest=59324/our-true-purpose

Necro Lords/Maldraxxus Unlock:
https://shadowlands.wowhead.com/quest=59609/urgently-needed

Kyrian/Bastion Unlock
https://shadowlands.wowhead.com/quest=57904/return-to-adrestes

Night Fae/Ardenweald Unlock
https://shadowlands.wowhead.com/quest=58160/for-queen-and-grove

Not sure how reliable this is as it comes from early beta testing and some parts of the covenant chain were changed since then.

**Comment by yoshimo** [comment]
Should look something like this

```		if expansion == CONSTANTS.EXPANSIONS.SHADOWLANDS then
			if IsQuestFlaggedCompleted(62017) then	--Necro Lords/Maldraxxus
				level = "60"
				quest = "|cffffff00|Hquest:59609:-1|h[No Rest For the Dead]|h|r" 
			elseif IsQuestFlaggedCompleted(62019) then --Night Fae/Ardenweald 
				level = "60"
				quest = "|cffffff00|Hquest:58160:-1|h[For Queen and Grove!]|h|r"
			elseif IsQuestFlaggedCompleted(62020) then --Venthyr/Revendreth
				level = "60"
				quest = "|cffffff00|Hquest:59324:-1|hOur True Purpose]|h|r"
			elseif IsQuestFlaggedCompleted(62023) then -- Kyrian/Bastion
				level = "60"
				quest = "|cffffff00|Hquest:57904:-1|h[Our Eternal Charge]|h|r"
			else
				level = "50"
				quest = "[TBD]"
			end
		end
```

**Comment by xmyno** [comment]
The world quest unlock spell has only 2 quests listed but maybe that's incomplete.
* 59609 - No Rest For the Dead
* 59324 - Our True Purpose
https://shadowlands.wowhead.com/spell=338946/world-quests

(there's also this one which has nothing listed: https://shadowlands.wowhead.com/spell=344241/world-quests)

**Comment by yoshimo** [comment]
The quest rewards for various covenant quests are also incomplete or wrong.
The Necrolords campaign changed class specific quests and rewards around a lot.
https://github.com/smaitch/Grail/issues/202 has a couple of recordings from various points in time on the beta realm.

For a second indicator of a lower level alt that skipped the main chain and levels with world quests active we might be able to use

> 		"+ Die Fäden des Schicksals(62704) <= Schicksalsschreiber Ro-Tahl(174871) 1670:20.41,50.28", -- [76]
> 			"\"threads of fate\" chosen, skip main story", -- [77]
> 			"New quest completed 58117 UNKNOWN NAME", -- [145]

Every other quest completed with that selection is completed outside Oribos while leveling

**Comment by yoshimo** [comment]
My old pictures on the topic:
![WQ_UNLOCK_Bastion_Kyrian](https://user-images.githubusercontent.com/17909/96352731-ec0feb00-10c5-11eb-9a21-5417a9f8a2b7.jpg)
![WQ_UNLOCK_Maldraxxus_NecroLords](https://user-images.githubusercontent.com/17909/96352733-eca88180-10c5-11eb-9040-e03f7a1f08f4.jpg)
![WQ_UNLOCK_Revendreth_Venthyr](https://user-images.githubusercontent.com/17909/96352734-ed411800-10c5-11eb-9073-7fb0646628a9.jpg)
![WQ_UNLOCK_Ardenweald_NighFae](https://user-images.githubusercontent.com/17909/96352736-ee724500-10c5-11eb-9331-4ef8f6c76aa5.jpg)

Spell data and names are partially out of date, but it should still be close to the current state.

**Comment by yoshimo** [comment]
I don't remember exactly the conditions but didn't we have a green paw icon for pet battle world quests back in BFA?

**Comment by xmyno** [comment]
> I don't remember exactly the conditions but didn't we have a green paw icon for pet battle world quests back in BFA?

Fixed. Typoed the all uppercase id in Blizzard code 😐 0ff692d6

**Comment by yoshimo** [comment]
We can filter rewards that contain anima by using C_Item.IsAnimaItemByID(itemlink) on the reward as there are quite a few items with varying amounts of anima rewarded.
Maybe by getting the spell link, even high/low.

**Comment by Amadeus-** [comment]
@yoshimo I think that everything for Shadowlands is now implemented into the addon.   If not, please feel free to open a new issue at the new "official" repository at https://github.com/Amadeus-/Broker_WorldQuests.   Or, you can fork that repository and create a pull request against it.

We're now at version 10.0.2.3 on Curseforge, which is now associated with my repo linked above.
