### ISSUE TITLE
Error which doesn't make sense.

### ISSUE THREAD

**Issue by Cluuey** [xmyno/Broker_WorldQuests#49]
I got this error while rushing to finish an assault WQ, I hadn't finished setting my rogue up yet since the patch and was clicking _Slice and Dice_ from the spell book when this error happened.
It doesn't make any sense to me as I doubt you're really looking at _StanceBar_ but you might be looking at the tooltip which is also mentioned in there.

```1x [ADDON_ACTION_BLOCKED] AddOn 'Broker_WorldQuests' tried to call the protected function 'StanceButton1:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\StanceBar.lua"]:93: in function `StanceBar_UpdateState'
[string "@FrameXML\StanceBar.lua"]:46: in function `StanceBar_Update'
[string "@FrameXML\ActionBarController.lua"]:109: in function `ActionBarController_UpdateAll'
[string "@FrameXML\SpellBookFrame.lua"]:585: in function `UpdateTooltip'
[string "@FrameXML\GameTooltip.lua"]:450: in function <FrameXML\GameTooltip.lua:429>```

**Comment by xmyno** [comment]
I don't think that's related. Sounds like the error happens in the C code of the Show() call from a stance button (https://www.townlong-yak.com/framexml/live/StanceBar.lua#93).

**Comment by Cluuey** [comment]
I didn't think it was but wasn't sure so I thought I should mention it.
