### ISSUE TITLE
BfA Assault zones missing.

### ISSUE THREAD

**Issue by Cluuey** [xmyno/Broker_WorldQuests#50]
Since the update for pre-patch the Uldum and Vale of Eternal Blossoms zones are no longer showing up.

Also the faction icons are missing for three factions and all using the faction icons for the rest, it doesn't stop it working I just thought I should mention it.
![image](https://user-images.githubusercontent.com/10675078/97068614-f3c71680-1614-11eb-9b9c-4166529de405.png)

**Comment by yoshimo** [comment]
Champions of Azeroth, Tortollan Seekers and Rustbolt resistance are available to both horde and alliance, therefore they don't need a faction icon :)

**Comment by Cluuey** [comment]
I'm aware of that, I'm quite sure before the patch that they had their own faction icons. The same icons they have next to each quest in the list.

**Comment by xmyno** [comment]
> Since the update for pre-patch the Uldum and Vale of Eternal Blossoms zones are no longer showing up.

I don't think I have a character with these unlocked, or are these the regular zones?
@Cluuey Can you get me the map ids by opening the world map with the specific zone open that these quests are in and paste this in chat: `/dump WorldMapFrame:GetMapID()`?

> Also the faction icons are missing for three factions

Faction icons in the settings were always just Horde/Alliance for the five each, only paragon bars have the faction specific icons.

**Comment by Cluuey** [comment]
1530 for Vale of Eternal Blossoms.
I haven't been to Uldum yet.

**Comment by yoshimo** [comment]
https://github.com/xmyno/Broker_WorldQuests/pull/42/files

I closed it because I thought I put it in the SL updates too

**Comment by xmyno** [comment]
Ah yes, missed that, sorry. Beta build `9.0.62` with the zones and some fixes is now processing on Curse.
