### ISSUE TITLE
One issue for new version

### ISSUE THREAD

**Issue by LasombraK** [xmyno/Broker_WorldQuests#51]
153x Broker_WorldQuests\WorldQuests.lua:818: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Broker_WorldQuests\WorldQuests.lua"]:818: in function <Broker_WorldQuests\WorldQuests.lua:598>
[string "@Broker_WorldQuests\WorldQuests.lua"]:1260: in function `UpdateQuestData'
[string "@Broker_WorldQuests\WorldQuests.lua"]:1442: in function `UpdateBlock'
[string "@Broker_WorldQuests\WorldQuests.lua"]:1428: in function `RunUpdate'
[string "@Broker_WorldQuests\WorldQuests.lua"]:2073: in function <Broker_WorldQuests\WorldQuests.lua:2065>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by xmyno** [comment]
Should be fixed in `9.0.63`. Thanks for the report and sorry.
