### ISSUE TITLE
Error with version 63.

### ISSUE THREAD

**Issue by Cluuey** [xmyno/Broker_WorldQuests#52]
I'm not exactly sure what triggered this as I was flying off at a tangent with the display showing, I've got it set to show on mouseover.
Perhaps my cursor was over a quest and a hostile mob at the same time, I'm really not sure. 😞 
Hopefully the error message will tell you enough.

```5x Usage: local title = C_QuestLog.GetTitleForLogIndex(questLogIndex)
[string "=[C]"]: ?
[string "@Broker_WorldQuests\WorldQuests.lua"]:1000: in function `UpdateBountyData'
[string "@Broker_WorldQuests\WorldQuests.lua"]:1249: in function `UpdateInfoPanel'
[string "@Broker_WorldQuests\WorldQuests.lua"]:1436: in function `UpdateBlock'
[string "@Broker_WorldQuests\WorldQuests.lua"]:1428: in function `RunUpdate'
[string "@Broker_WorldQuests\WorldQuests.lua"]:2074: in function <Broker_WorldQuests\WorldQuests.lua:2066>

Locals:
(*temporary) = "Usage: local title = C_QuestLog.GetTitleForLogIndex(questLogIndex)"
```

**Comment by Cluuey** [comment]
I just had this error happen when I logged my rogue in, I was in my Garrison!
I heard the _fatality_ error sound from BugSack before my UI had drawn, it's up to a count of nine now.

**Comment by Amadeus-** [comment]
I'm going to assume this got fixed somewhere along the line, because I've never had it happen.   But, if it does happen again, please go over to the new "official" repository at https://github.com/Amadeus-/Broker_WorldQuests and open a new issue there.
