### ISSUE TITLE
Tooltip/hover error

### ISSUE THREAD

**Issue by tylerancell** [xmyno/Broker_WorldQuests#53]
Getting the error below when hovering over the world quest rewards:

`10x Usage: GameTooltip:SetHyperlink(link)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@Broker_WorldQuests\WorldQuests.lua"]:506: in function <Broker_WorldQuests\WorldQuests.lua:500>
[string "@Broker_WorldQuests\WorldQuests.lua"]:1616: in function <Broker_WorldQuests\WorldQuests.lua:1612>

Locals:
(*temporary) = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 SetText = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 SetLootItem = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 BottomOverlay = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 updateTooltip = 0.172000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 comparing = false
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 __tooltipUpdated = false
 Hide = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 template = "Transparent"
 textRight2Font = "GameTooltipText"
 SetTradeTargetItem = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 SetMerchantCostItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 SetToyByItemID = <function> defined =[C]:-1
 Center = <unnamed> {
 }
 0 = <userdata>
 SetInboxItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetBackpackToken = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 SetUnitBuff = <function> defined =[C]:-1
 TopLeftCorner = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 StatusBar = GameTooltipStatusBar {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 BottomEdge = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetQuestLogItem = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 TopRightCorner = <unnamed> {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:289
 customBackdropAlpha = 0.800000
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = nil
`

**Comment by yoshimo** [comment]
Does this occur reliably for certain rewards?

**Comment by Amadeus-** [comment]
I've seen this happen too.  Once it happens, it happens for all the links.  But, then next time I come to the game, it's all fine.  I'm going to try and track it down next time.

**Comment by Amadeus-** [comment]
I'm not sure if this is still happening with Dragonflight.   But, if it does happen again, please go over to the new "official" repository at https://github.com/Amadeus-/Broker_WorldQuests and open a new issue there.

I can say that when I tried tracking it down back during Shadowlands my best guess is that it was a WoW bug, because I could find no reason at all for it to be happening otherwise (especially happening so randomly.)
