### ISSUE TITLE
Linebreaks for rewards would be nice

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#55]
As you can see with the quest on the top, long reward names almost hide other rewards from the same quest.
Grateful Offerings in this case

![grafik](https://user-images.githubusercontent.com/17909/108035886-ce34a180-7037-11eb-8492-15b8e6aa346e.png)

**Comment by yoshimo** [comment]
Of course quest names might be nice too

**Comment by Amadeus-** [comment]
I increased the width of the window as of today's big update.
