### ISSUE TITLE
High CPU load interference with Dugi Guide waypoint arrow

### ISSUE THREAD

**Issue by Weissrolf** [xmyno/Broker_WorldQuests#6]
R19: Causes a short CPU load spike in Dugi Guide's waypoint arrow when the broker tooltip is opened.
R20/21: Cause permanently high CPU load of DG waypoint arrow even when the broker tooltip is not open.

So whatever Broker WorldQuest is doing (constantly polling the map information maybe?), it considerably interferes with the other addon.

**Comment by Weissrolf** [comment]
Just to mention: While the map is open the CPU load decreases considerably.

**Comment by ceylina** [comment]
Not just interfering with other addons. I noticed a huge spike today while running world quests and saw this addon spike before being forcefully garbage collected.

I wrote about it in the comments

> r21 is starting to use a ton of memory before being garbage collected. What was added in the last few updates that causes this and is it possible to add the ability to disable it? If it is calculating AP, I will happily do without if it means it doesn't eat up memory.
> I understand memory usage is not critical these days but the rapid way this addon starts eating it makes me concerned. I am also noticing it jump to over 15 MB usage before recycling which is insane for this type of addon.
> 
> Ok to add on to this, I tried r18-r21
> 
> r18 does not have any memory leak. r19 will climb whenever you mouseover the broker display and show the tooltip.  It's not terrible and when recycling happens memory usage goes back to normal so it is not an issue.
> r20 is where this memory spike starts to happen and r21 is really bad.

**Comment by xmyno** [comment]
Memory issue/too many updates should be fixed in r22.
Have not had the chance to look into Dugi. Might be because updating the list causes a few WORLD_MAP_UPDATE events and this triggers some CPU-intensive work in Dugis? Not sure.

**Comment by Weissrolf** [comment]
R22 seems to have fixed the Dugi arrow issues. Like the world map updates to be blamed. There still is a short (big) spike when the tooltip opens, but that's just a split second anyway.
