### ISSUE TITLE
r21 : no loot

### ISSUE THREAD

**Issue by Erwane** [xmyno/Broker_WorldQuests#7]
r21 doesn't display loots with elvui

**Comment by xmyno** [comment]
Can you tell me what locale you are using?

**Comment by Erwane** [comment]
french for textes and dialogs

**Comment by xmyno** [comment]
Thanks. Can you give r23 a try? Should have a fix for that.

**Comment by Erwane** [comment]
fixed by de774d7bec

Thanks
